### ISSUE TITLE
Codifica dei caratteri

### ISSUE THREAD

**Issue by AR-9217** [Neurone/stellaris-italian-translation#12]
Nella pagina principale c'è scritto che bisogna usare il formato UTF-8 ma nella wiki ufficiale viene indicato l' UTF-8-BOM. E' un errore?

**Comment by Neurone** [comment]
Grazie della segnalazione, chiarisco nelle istruzioni. Il charset corretto è **UTF-8** ma i file di testo possono usare dei caratteri speciali all'inizio per determinare l'ordine di scrittura dei byte, il [BOM](https://it.wikipedia.org/wiki/Byte_Order_Mark) appunto. Usando il metodo del "copia e incolla" questo dettaglio è trascurabile, e solitamente anche se si modificano file esistenti l'editor non tocca il BOM se è presente.
