### ISSUE TITLE
Piccola correzione

### ISSUE THREAD

**Issue by AR-9217** [Neurone/stellaris-italian-translation#8]
Ho trovato un errore di battitura nel file "utopia_megastructures_l_english.yml" riguarda il dialogo che appare dopo la costruzione del nucleo del Nexus. Anziché "pressione intensa" c'è scritto "pressione intesa". Ho editato il file ma non mi è ben chiaro come devo fare il pull, nel dubbio allego qui...

Inoltre se vi dovesse servire una mano con la traduzione dell'ultimo dlc sono più che disponibile!

[utopia_megastructures_l_english.txt](https://github.com/Neurone/stellaris-italian-translation/files/4686199/utopia_megastructures_l_english.txt)

**Comment by Neurone** [comment]
Grazie mille, ho aggiornato. Per il resto, Stellaris è andato avanti dall'ultima grande traduzione della 2.5, in particolare con il DLC Federations. Attualmente però non ce l'ho, quindi non posso verificare la bontà del tutto... :D Se però ti interessa ti posso dare i dettagli di come contribuire, ma è tanta roba (vuoto per pieno parliamo di 400.000 battute!).

Per le prossime correzioni, hai diverse opzioni puoi farle anche direttamente online per semplicità (se non sono troppo complesse è comodo anche così). Ti scrivo una guida dettagliata, magari serve anche ad altri, ma nel mentre in sintesi:
1) selezioni il file che vuoi modificare
2) premi sull'icona a destra di modifica e fai le modifiche che devi (le starai facendo automaticamente in realtà su una tua versione forkata di questo repo)
3) quando finisci le modifiche ti proporrà automaticamente di salvare e di proporre una pull request a questo repo
4) una volta accettata la pull request, le tue modifiche vengono unite a quelle principali e github ti propone di buttare la versione che hai tu, così per le prossime volte riparti da una versione sempre aggiornata

**Comment by AR-9217** [comment]
Mi dia tutti i dettagli appena può grazie! Ho già tutti i file yml necessari

Il giorno ven 29 mag 2020 alle ore 00:20 Giuseppe Bertone <
notifications@github.com> ha scritto:

**Comment by Neurone** [comment]
Ho inserito nella [pagina principale](https://github.com/Neurone/stellaris-italian-translation#contribuire-alla-traduzione ) tutti i dettagli per contribuire alle traduzioni.

**Comment by AR-9217** [comment]
Grazie mille!

Il giorno dom 31 mag 2020 alle ore 04:13 Giuseppe Bertone <
notifications@github.com> ha scritto:
